### ISSUE TITLE
Unfinished script + codhale / dropwizard dont have a plugin for jenkins

### ISSUE THREAD

**Issue by innovia** [samrocketman/jenkins-influx-metrics#1]
Hi

1) this script only prints the flags 

2) it says its based on metrics api plugin - installed but does not provide any api server accesss

3) codhale site is down -> dropwizard has no plugin for jenkins

how did you get your to work?

**Comment by samrocketman** [comment]
Hey, this script is a work in progress and it's been a while since I've picked it up again.  In general, I've documented how it's supposed to work.  I'll pick it up again eventually but right now please consider it pre-alpha.

I tend to write a lot of documentation first to sort out my ideas for how a program should work.  It makes it easy to change as I develop it.

**Comment by samrocketman** [comment]
I went ahead and added a warning to the README so people know right away that the project isn't usable.
